server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/g07_qa?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB      # 单个文件最大限制
      max-request-size: 50MB   # 单次请求总大小限制

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: g07-knowledge

ai:
  api:
    url: https://api.deepseek.com
    key: sk-449c29805ae64751a48f4ce7a7d39503
  model: deepseek-chat
  max_tokens: 2048
  temperature: 0.7